sean = 
tony = Provider.create(name: "Marcus Massage", email: "mmassage@gmail.com", business_name: "Massages By Marcus", location: "5456 Lincoln Ave, Milwaukee WI",password: "password123", phone_number: "555-555-5555")
tony.services << Service.create(name: "Swedish Massage (30 min)", description: "Swedish massage is a relaxing full-body massage designed to manipulate the superficial layers of the muscles to aide in both mental and physical health. Benefits of Swedish massage include increased circulation, mental and physical relaxation, decreased stress and muscle tension, and improved range of motion. ", price: 45)
tony.services << Service.create(name: "Swedish Massage (60 min)", description: "Swedish massage is a relaxing full-body massage designed to manipulate the superficial layers of the muscles to aide in both mental and physical health. Benefits of Swedish massage include increased circulation, mental and physical relaxation, decreased stress and muscle tension, and improved range of motion. ", price: 75)
tony.services << Service.create(name: "Swedish Massage (90 min)", description: "Swedish massage is a relaxing full-body massage designed to manipulate the superficial layers of the muscles to aide in both mental and physical health. Benefits of Swedish massage include increased circulation, mental and physical relaxation, decreased stress and muscle tension, and improved range of motion. ", price: 105)
tony.services << Service.create(name: "Deep Tissue Massage (30 min)", description: "Deep tissue massage focuses on specific ailments of the body. This type of massage uses a firm or deep pressure to sink into the deepest layers of muscles and fascia. The belief that deep pressure equals pain, is a myth. Deep tissue massage focuses on healing chronic pain, sports injuries or stresses, migraines, neck and shoulder pain, and more.", price: 55)
tony.services << Service.create(name: "Deep Tissue Massage (30 min)", description: "Deep tissue massage focuses on specific ailments of the body. This type of massage uses a firm or deep pressure to sink into the deepest layers of muscles and fascia. The belief that deep pressure equals pain, is a myth. Deep tissue massage focuses on healing chronic pain, sports injuries or stresses, migraines, neck and shoulder pain, and more.", price: 95)
tony.services << Service.create(name: "Deep Tissue Massage (30 min)", description: "Deep tissue massage focuses on specific ailments of the body. This type of massage uses a firm or deep pressure to sink into the deepest layers of muscles and fascia. The belief that deep pressure equals pain, is a myth. Deep tissue massage focuses on healing chronic pain, sports injuries or stresses, migraines, neck and shoulder pain, and more.", price: 135)
tony.save

